"""
WHILE RESIZING THE qUEUE THAT HAS BEEN WRAPED AROUND DURING
ITS OPERTIONS WE ALLIGN THE FRONT OF THE OLD ARRAY TO THE
0TH INDEX OF THE NEW RESIZED ARRAY. iF WE ELIMINATE THE LINE
OF CODE THAT HAS BEEN SUGGESTED IN THE PROBLEM  WE WOULD NOT
BE ABLE TO ACCOMPLISH THIS. aND THAT WAY OUR IMPLEMENTATION O
F RESIZING THE qUEUE WILL BE FLAWED
 

"""
